travis:
  secure:
    BINSTAR_TOKEN: I9yUkpU70wfRjmINw8WOrmlyQbGnTN+5AzgPO/Z1s7OFMtN0SQ+3aEhWbQDfQo+PkGqUjruo4nKqsk9anX/xq9bSqNy+3FAyfFw/jEeZimu0nqlh778pu8m2wQURr/X35ULl30F0Qzi3VuNUgrosHFHQ8a0Y7ww52yh4EXRo5+BbXbe9cZzFcIYX2itOffzJtlIqHDFbww4CHb/5tV2lO2B7DwcnrmYwIZDFwtlD7drcx3MeRxn7bcDN1b1NnNr0SXtwZnXQNsvKMvs/mFlGtX9MJ4KdZIwaGR2P8bF0V1cObxNzO0WYEYptZqLo9yQ6bPhU6fyJDr0ASVRGYnd+FWO7z9i7UNUwaLe3zr421V51C5EHjcOebMsKwm8jEJV93d9kpCG83LDP5F5F0bd0HlCBzd46vnPNgjBS+l3A8o8R32Lo+zEnGeJBmz7MZH9F5nI3qF1QKU3+XL9JNEGZ2YVT+TGYt0D3GH0P0D+UJ0fYWqxMj1OUy/JF8k4EeS+04FatYP6at9Nj8mzIkp6O9PRu9/icgBhQojFoa9gcknxkLvkI/Drg1qwJDoFJzW8wjCOkin6EPvyhdjeg0PMp2depC1DItc/gn/AA/uQaGU9kb3sT9dGsl1G+SHQpHhxqn/VbSTpb67x01H2g6NquDd/U1NBhvKSwo6g0nrSVHl4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
