travis:
  secure:
    BINSTAR_TOKEN: UjVN/KUgR8dOvSYwKvd7N2FnGRTaU+7S3SI+s9bXC3GyQ6lzuuP9NjNpaqRe0NjI9eQlLMMDoIBfZOnsMHiuF+lleJxdo/qAZR18UTSOQ6CXdq1o0ghp6TFFvXHpKMjT59WKxG2z52Ln5pfb+BSDqhVbxzJ+48e15FePPWrGrDuHMDDOJFrfgvp+f+xc+jWRbEdRZQThUIcbb+CO+h+DgOUEL7ZG83WOMoxxEmRNUONw4QAd45dD9P9+upi7jIkGJSfVwcSXi0YkzZhcrVXjK0PYdO7guJmRPvOnyrXGTacBIbqjh70ibEl4RdordZxsbQ8jMOLaBH33Wt+n7RWe9PEC/AuT38aeyTzcEAYn75X1waM1TGcQDwosQ2h4U7W7jAeffTpthYuRsmKFbRYh6zRf746P8tW4JFu/DpXRyO2bV9svJRPNz2ejWXK36bhQNxRSwoUpHgQI1jsL6Q2I7PR2LwiFAVaGZXHKR7zs4VrNffNcNclMq/t+5XGPu+f4mPYTL1MClkgGpWsu7ZGdaokXSopRrqQ6D42iAvwyE52BrayJC29YIX6OkLf2T75i5+wUo93G42zyO8t5IqXenCYyIh2jwm7RqDZZ1Fy2rL9HxHX9e+F7Uurt1i5J6693Lu4PaSom05sVUQQGyM0UHnyU5lzkoy65ufIvV2hVSxI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
